### ISSUE TITLE
add a real mailer

### ISSUE THREAD

**Issue by cloughy** [greg0ire/dockerony#19]
Mailcatcher is too good an email client. We need to be able to test with other clients like outlook, gmail, whatever

**Comment by greg0ire** [comment]
@jngermon says https://hub.docker.com/r/catatnight/postfix/ could do the trick

**Comment by cloughy** [comment]
:)

Anne-Claire Irrmann

**Comment by jngermon** [comment]
You ca see my configuration of that mailer here : https://github.com/jngermon/docker-gitlab/blob/mailer/docker-compose.yml.dist#L40-L46

I have just followed this note https://github.com/loomio/loomio/wiki/Setup-an-SMTP-server-with-Docker

**Comment by greg0ire** [comment]
Thanks @jngermon !
